import React from 'react';
import Head from 'next/head';
import { Footer, Header } from '../components';

interface ILayout {
  children: React.ReactNode;
  name: String;
}

const Layout: React.FC<ILayout> = ({ children, name }) => {
  return (
    <div className="container">
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="main">{children}</main>
      <Footer />
    </div>
  );
};

export default Layout;
