import React from 'react';
import Head from 'next/head';
import { Header } from '../components/Header';
import { Footer } from '../components/Footer';

interface ILayout {
  children: React.ReactNode;
  name: String;
}

export const Layout: React.FC<ILayout> = ({ children, name }) => {
  return (
    <div className="container">
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header />
      <main className="main">{children}</main>
      <Footer />
    </div>
  );
};
